In [5]:
import pandas as pd
import numpy as np

medicine = pd.read_csv("../dataset/medicine_info.csv")
medicine.head(46)

,Medicine,Generic_Name,Brand_Name,Medicine_Type,Used_For,Dosage,Side_Effects
0,Paracetamol,Paracetamol,"Dolo 650,Crocin",Analgesic,"Fever,Headache",500-650 mg,"Nausea,Rash"
1,Ibuprofen,Ibuprofen,"Brufen,Advil",NSAID,"Pain,Inflammation",200-400 mg,Heartburn
2,Metformin,Metformin,Glycomet,Antidiabetic,Type 2 Diabetes,500 mg,Diarrhea
3,Pantoprazole,Pantoprazole,Pantocid,PPI,"GERD,Acidity",40 mg,Headache
4,Amoxicillin,Amoxicillin,"Amoxil,Mox",Antibiotic,Bacterial Infection,500 mg,"Diarrhea,Nausea"
5,Azithromycin,Azithromycin,"Azee,Zithromax",Antibiotic,Respiratory Infection,500 mg,Stomach Pain
6,Cetirizine,Cetirizine,"Cetzine,Zyrtec",Antihistamine,"Allergy,Sneezing",10 mg,Drowsiness
7,Levocetirizine,Levocetirizine,"Xyzal,Levocet",Antihistamine,Allergic Rhinitis,5 mg,Sleepiness
8,Omeprazole,Omeprazole,"Omez,Prilosec",PPI,"Acidity,Ulcer",20 mg,"Headache,Nausea"
9,Rabeprazole,Rabeprazole,"Rablet,Razo",PPI,"GERD,Acidity",20 mg,Constipation
10,Esomeprazole,Esomeprazole,"Nexpro,Nexium",PPI,Acid Reflux,40 mg,Headache
11,Domperidone,Domperidone,"Domstal,Motilium",Antiemetic,"Vomiting,Nausea",10 mg,Dry Mouth
12,Ondansetron,Ondansetron,"Ondem,Emeset",Antiemetic,"Nausea,Vomiting",4-8 mg,Constipation
13,Dicyclomine,Dicyclomine,Cyclopam,Antispasmodic,Abdominal Pain,20 mg,Dry Mouth
14,Loperamide,Loperamide,Imodium,Antidiarrheal,Diarrhea,2 mg,Constipation
15,ORS,Oral Rehydration Salts,Electral,Electrolyte,"Dehydration,Diarrhea",As Directed,Rare
16,Amlodipine,Amlodipine,Norvasc,Antihypertensive,High Blood Pressure,5 mg,"Swelling,Dizziness"
17,Telmisartan,Telmisartan,Telma,ARB,Hypertension,40 mg,Low Blood Pressure
18,Losartan,Losartan,Losar,ARB,Hypertension,50 mg,Dizziness
19,Atenolol,Atenolol,Aten,Beta Blocker,Hypertension,50 mg,Fatigue
20,Atorvastatin,Atorvastatin,Lipitor,Statin,High Cholesterol,10-20 mg,Muscle Pain
21,Rosuvastatin,Rosuvastatin,Rosuvas,Statin,High Cholesterol,10 mg,Muscle Weakness
22,Aspirin,Aspirin,Ecosprin,Antiplatelet,Heart Disease Prevention,75 mg,Bleeding
23,Clopidogrel,Clopidogrel,Clopilet,Antiplatelet,Stroke Prevention,75 mg,Bleeding
24,Insulin,Human Insulin,"Huminsulin,Novorapid",Hormone,Diabetes,As Prescribed,Hypoglycemia
25,Glimepiride,Glimepiride,Amaryl,Antidiabetic,Type 2 Diabetes,1-2 mg,Low Blood Sugar
26,Gliclazide,Gliclazide,Diamicron,Antidiabetic,Diabetes,80 mg,Hypoglycemia
27,Pioglitazone,Pioglitazone,Pioz,Antidiabetic,Type 2 Diabetes,15 mg,Weight Gain
28,Salbutamol,Salbutamol,"Asthalin,Ventolin",Bronchodilator,Asthma,2 mg,Tremors
29,Budesonide,Budesonide,Budecort,Corticosteroid,Asthma,200 mcg,Hoarseness
30,Montelukast,Montelukast,Montek,Leukotriene Antagonist,"Asthma,Allergy",10 mg,Headache
31,Dexamethasone,Dexamethasone,Decadron,Corticosteroid,Inflammation,0.5 mg,Weight Gain
32,Prednisolone,Prednisolone,Wysolone,Corticosteroid,"Allergy,Inflammation",10 mg,Increased Appetite
33,Diclofenac,Diclofenac,"Voveran,Voltaren",NSAID,Joint Pain,50 mg,Stomach Pain
34,Aceclofenac,Aceclofenac,Hifenac,NSAID,Arthritis,100 mg,Nausea
35,Tramadol,Tramadol,Ultram,Opioid Analgesic,Severe Pain,50 mg,Dizziness
36,Amitriptyline,Amitriptyline,Tryptomer,Antidepressant,"Depression,Nerve Pain",25 mg,Sleepiness
37,Sertraline,Sertraline,Zoloft,SSRI,"Depression,Anxiety",50 mg,Insomnia
38,Fluoxetine,Fluoxetine,Prozac,SSRI,Depression,20 mg,Nausea
39,Alprazolam,Alprazolam,Alprax,Benzodiazepine,Anxiety,0.25 mg,Drowsiness
40,Clonazepam,Clonazepam,Clonotril,Benzodiazepine,Panic Disorder,0.5 mg,Sleepiness
41,Vitamin C,Ascorbic Acid,Limcee,Vitamin,Vitamin C Deficiency,500 mg,Stomach Upset
42,Vitamin D3,Cholecalciferol,Uprise D3,Vitamin,Vitamin D Deficiency,60000 IU Weekly,Constipation
43,Calcium,Calcium Carbonate,Shelcal,Supplement,Calcium Deficiency,500 mg,Constipation
44,Iron,Ferrous Sulphate,Orofer,Supplement,Iron Deficiency Anemia,100 mg,Dark Stool
45,Zinc,Zinc Sulphate,Zincovit,Supplement,Zinc Deficiency,50 mg,Nausea

In [6]:
medicine.shape

(47, 7)

In [7]:
medicine.columns

Index(['Medicine', 'Generic_Name', 'Brand_Name', 'Medicine_Type', 'Used_For',
       'Dosage', 'Side_Effects'],
      dtype='str')

In [8]:
medicine.isnull().sum()

Medicine         0
Generic_Name     0
Brand_Name       0
Medicine_Type    0
Used_For         0
Dosage           0
Side_Effects     0
dtype: int64

In [9]:
name = "Paracetamol"

medicine[
    medicine["Medicine"].str.contains(name, case=False)
]

,Medicine,Generic_Name,Brand_Name,Medicine_Type,Used_For,Dosage,Side_Effects
0,Paracetamol,Paracetamol,"Dolo 650,Crocin",Analgesic,"Fever,Headache",500-650 mg,"Nausea,Rash"

In [10]:
brand = "Crocin"

medicine[
    medicine["Brand_Name"].str.contains(brand, case=False)
]

,Medicine,Generic_Name,Brand_Name,Medicine_Type,Used_For,Dosage,Side_Effects
0,Paracetamol,Paracetamol,"Dolo 650,Crocin",Analgesic,"Fever,Headache",500-650 mg,"Nausea,Rash"

In [11]:
disease = "Fever"

medicine[
    medicine["Used_For"].str.contains(disease, case=False)
]

,Medicine,Generic_Name,Brand_Name,Medicine_Type,Used_For,Dosage,Side_Effects
0,Paracetamol,Paracetamol,"Dolo 650,Crocin",Analgesic,"Fever,Headache",500-650 mg,"Nausea,Rash"

In [12]:
def medicine_search(name):

    result = medicine[
        medicine["Medicine"].str.contains(name, case=False)
    ]

    if result.empty:
        print("Medicine Not Found")
    else:
        return result

In [13]:
medicine_search("Paracetamol")

,Medicine,Generic_Name,Brand_Name,Medicine_Type,Used_For,Dosage,Side_Effects
0,Paracetamol,Paracetamol,"Dolo 650,Crocin",Analgesic,"Fever,Headache",500-650 mg,"Nausea,Rash"

In [14]:
medicine.to_csv("../dataset/medicine_clean.csv", index=False)